#IF YOURE WONDERING WHERE ALL THE NON-CONSCRIPT JOBS WENT
#JUST RE-ENABLE THEM AND SET editorHidden: false
#YOU'RE WELCOME
# .2 - 2025

- type: department
  id: Command
  name: department-Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - HeadOfPersonnel # Not shown but needed here for playtime
  - HeadOfSecurity # Not shown but needed here for playtime
#  - ChiefMedicalOfficer
  primary: false
  weight: 100
  editorHidden: true

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  weight: -94
  primary: false
  editorHidden: true

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#52B4E9"
  weight: -93
  editorHidden: true

- type: department
  id: CommandCorp
  name: department-CM
  description: department-cm-description
  color: "#FFD580"
  weight: 102
  primary: false
  roles:
  - Commissar
  - Undercommissar
  - Prefect

- type: department
  id: PeacekeepingCorps
  name: department-PC 
  description: department-pc-description
  color: "#DE3A3A"
  weight: 90
  primary: false
  roles:
  - Sergeant