- type: job
  id: Commissar
  name: job-name-cm-commissar
  description: job-description-cm-commissar
  playTimeTracker: JobCommissar
  icon: "JobIconCommissar"
  weight: 102
  startingGear: CommissarGear
  canBeAntag: false
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 75h
    - !type:RoleTimeRequirement
      role: JobUndercommissar
      time: 20h
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CommissarGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCommissar
    pocket1: WeaponPistolMk58
    shoes: ClothingShoesBootsLaceup
    id: CommissarIDCard
  storage:
    back:
    - Flash
    - MagazinePistol
